### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by naazy** [dwyl/learn-postgresql#1]
- pgAdminIII 
- postgres App i.e. psql (the need to connect to the SQL server on port 5432)
- Some basic CRUD commands e.g. create database/table 
- Example (with focus on Hapi and pg node module)
- Screenshots

**Comment by des-des** [comment]
@naazy have you looked at sequelize?

**Comment by mantagen** [comment]
@naazy http://www.sitepoint.com/3-javascript-orms-you-might-not-know/
(don't know which js ORMs you would know if you didn't know any of these)

**Comment by naazy** [comment]
@des-des no I haven't! Would you recommend?

**Comment by nelsonic** [comment]
@des-des six-months-later, would you _still_ recommend using `sequelize`...?

**Comment by mantagen** [comment]
Good question

**Comment by des-des** [comment]
@nelsonic I am not sure any good orms for node exist :(. I would try hard to find an alternative to sequelise if I started a new project, its bloated and painful to use. That said, unless you are working on a very small project, I do not think handwriting all your queries is a good idea, I feel like there should be an abstraction above sql to work with. Something that was not too complex / big but abstracted some sql stuff away would be perfect.

**Comment by des-des** [comment]
http://knexjs.org/ would be the first thing I looked into

**Comment by nelsonic** [comment]
@des-des I had a look at Knex the other day.
Code seemed OK to me. but what screamed of "_unmaintained_" was:
[![npm version](http://img.shields.io/npm/v/knex.svg)](https://npmjs.org/package/knex)
[![Build Status](https://travis-ci.org/tgriesser/knex.svg?branch=master)](https://travis-ci.org/tgriesser/knex)
[![Coverage Status](https://coveralls.io/repos/tgriesser/knex/badge.svg?branch=master)](https://coveralls.io/r/tgriesser/knex?branch=master)
[![Dependencies Status](https://david-dm.org/tgriesser/knex.svg)](https://david-dm.org/tgriesser/knex)
[![Gitter chat](https://badges.gitter.im/tgriesser/knex.svg)](https://gitter.im/tgriesser/knex)

+ Not following Semver (_so we will have to read code to know when a backward-incompatible change is made..._)
+ The other badges speak for themselves ... 😞 

**_37_ Open PRs** at the time of writing going back 2 years. and reading through the features being added it's doing _way_ too many things ... 😕 

I'd be _stoked_ to read your findings when you _are_ able to investigate the available options! 👍

**Comment by nelsonic** [comment]
We've been using Ecto in the context of our Phoenix apps and `pg` with `pg-escape` in Node.js
for an _example_ of this see: https://github.com/nelsonic/time-mvp/blob/master/server/db.js#L46
