### ISSUE TITLE
PostgreSQL failed user login (Windows) 

### ISSUE THREAD

**Issue by MikeRund** [dwyl/learn-postgresql#112]
For anyone that ran into the same issue as me, after installing PostgreSQL and setting up password I still ran into an authorization error. The issue was that while my default user existed, a corresponding database hadn't been initialized. To fix I removed authorization following these instructions:

 https://www.postgresqltutorial.com/postgresql-administration/postgresql-reset-password/

And then created a database (where {user} is your username):

`CREATE DATABASE {user} OWNER {user};`

After logging out, resetting the auth method and restarting the issue was fixed.

**Comment by nelsonic** [comment]
@MikeRund please ensure you include what you researched/found and what the ultimate solution was `before` closing an issue otherwise it's a dead-end. https://xkcd.com/979/

![image](https://github.com/user-attachments/assets/979eaf35-6faf-4511-ad87-d9e8f57bafe7)
