### ISSUE TITLE
zsh: command not found: psql

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-postgresql#116]
On a `new` Mac when attempting to connect to `Postgres` from `Terminal`, we see the following error: 

```sh
zsh: command not found: psql
```

`psql` _appears_ to not be installed. 🤷‍♂️

**Comment by nelsonic** [comment]
first result on `Google`: https://stackoverflow.com/questions/36155219/psql-command-not-found-mac

**Comment by nelsonic** [comment]
The most _helpful_ answer for someone using a `Mac` is: https://stackoverflow.com/a/50031218/28383123
Because we have installed the `Postgres.app` https://postgresapp.com

In our case, we didn't yet have a `.bash_profile` file in the home folder so created it with:

```sh
vi ~/.bash_profile
```

Paste the following into the editor:

```sh
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
```

> **Note**: if you're `new` to `vi`/`VIM`, you save the file and exit
by hitting the <kbd>ESC</kbd> key and typing `:wq` followed by <kbd>Return</kbd> key

Then, to ensure the command is available in the _current_ `Terminal` session, run:

```sh
source ~/.bash_profile
```

_Confirm_ your `Terminal` now _knows_ where the `psql` command is using the following:

```sh
which psql
```

You should see output similar to the following:

```sh
/Applications/Postgres.app/Contents/Versions/latest/bin/psql
```

So it should work as expected now. ✅

**Comment by ndrean** [comment]
Why .bash_profile since you use zsh?

**Comment by nelsonic** [comment]
Very happy to use zshrc instead. Just wanted a general solution so I could move in with my main quest. 😉
