### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/learn-postgresql#13]
![screen shot 2016-10-21 at 16 34 44](https://cloud.githubusercontent.com/assets/12450298/19604289/82ee3fb4-97ac-11e6-9c4f-a37310a5ddde.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-21 at 16 37 20](https://cloud.githubusercontent.com/assets/12450298/19604332/b499dd8e-97ac-11e6-831f-baa8952e5f45.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-21 at 16 38 39](https://cloud.githubusercontent.com/assets/12450298/19604398/fcb967e2-97ac-11e6-9a57-b7557ad45931.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-21 at 16 41 07](https://cloud.githubusercontent.com/assets/12450298/19604471/50e2f946-97ad-11e6-9a5a-b5db749cf41a.png)

**Comment by jackcarlisle** [comment]
<img width="662" alt="screen shot 2016-10-21 at 16 43 04" src="https://cloud.githubusercontent.com/assets/12450298/19604512/86f87326-97ad-11e6-84c7-7e206cdf4f0c.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-21 at 16 46 36](https://cloud.githubusercontent.com/assets/12450298/19604617/f5842970-97ad-11e6-86a5-73eb6dce4852.png)

**Comment by nelsonic** [comment]
@jackcarlisle I would use http://postgresapp.com/ on mac. (_I think you've already seen it..._)

Please add `Linux` and `Windows` section(s) a _request_ help from people who have Linux/Windows to update the section(s).
leave some starter links to help people until the sections are updated:
+ https://wiki.postgresql.org/wiki/Detailed_installation_guides
+ https://www.postgresql.org/download/

**Comment by jackcarlisle** [comment]
@nelsonic sounds good I will do! 👍

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-24 at 11 08 36](https://cloud.githubusercontent.com/assets/12450298/19641848/6d3cfa4a-99da-11e6-858f-3ff2ada026be.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-24 at 11 15 36](https://cloud.githubusercontent.com/assets/12450298/19642044/463eceae-99db-11e6-8907-bb3a6cc532a7.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-24 at 11 42 19](https://cloud.githubusercontent.com/assets/12450298/19642816/f8ac0c66-99de-11e6-87e2-db55e6abc27b.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-24 at 15 50 40](https://cloud.githubusercontent.com/assets/12450298/19650613/ce278678-9a01-11e6-89ad-b124c0adcfe5.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-10-24 at 15 57 07](https://cloud.githubusercontent.com/assets/12450298/19650852/9c340708-9a02-11e6-8f06-75f1e30a86b3.png)

**Comment by nelsonic** [comment]
Thanks for adding these screenshots Jack! re-open if necessary. 👍
