### ISSUE TITLE
No setup info on Ubuntu :'(

### ISSUE THREAD

**Issue by mk4111** [dwyl/learn-postgresql#19]
Currently there's no info for Ubuntu-users, on how to setup/install Postgres...
It would be great if there was some description on:

- how to install Postgres on our machines
- how to access the client

**Comment by nelsonic** [comment]
@mk4111 _indeed_... we that's why we _need_ you! when you PR the update please `fixes #2` (_thanks!_)

**Comment by mk4111** [comment]
Epic! I'll start writing up :D

**Comment by mk4111** [comment]
Hi @nelsonic - sorry I didn't document the user journey to finding out the solution that worked best for me! Will be sure to do so on the progress we make today!
