### ISSUE TITLE
how to load an existing schema into a new database when starting an existing app for the first time

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-postgresql#26]
We need a good way of loading an existing database schema and/or data into a database 
when a _new_ member of the team is booting the app for the first time
this is _obvs_ also applicable to testing your app in CI ... 🍏 

The way we have done this is: [create_table.js](https://github.com/dwyl/hapi-login-example-postgres/blob/acf3797dcfa1efb82a3667c3c040fb004270a9ba/test/_create_table.js) but we don't think is a particularly good way of doing it... 🤔 

If anyone has a _simpler_ more effective or _faster_ way of doing this please let us know! ❤️  ✅

**Comment by AnianZ** [comment]
I usually use migrations and seeds with [knex.js](http://knexjs.org/). That makes changes to the database more portable and forces me to keep them revertible. Currently I don't have an active CI pipeline yet but it works great for provisioning vagrantfiles.

If a query builder like knex is too much for you, there sure is a simpler solution for migrations and seeds with pure SQL or just implement your own.

**Comment by nelsonic** [comment]
Ecto Migrations/Seeds have us covered with this. 💧 ❤️ ✅
