### ISSUE TITLE
"Port in use" PostgresSQL 13

### ISSUE THREAD

**Issue by ayelen3976** [dwyl/learn-postgresql#78]
Hi, can any help me? I cant see my db . I just want see 
<img width="1440" alt="Captura de Pantalla 2020-12-26 a la(s) 13 34 10" src="https://user-images.githubusercontent.com/51239110/103156013-375c0f00-4783-11eb-8f0a-e89d454a29e9.png">
databases that I have
<img width="1440" alt="Captura de Pantalla 2020-12-26 a la(s) 13 54 51" src="https://user-images.githubusercontent.com/51239110/103155984-0085f900-4783-11eb-826b-213eb72aa72e.png">

**Comment by nelsonic** [comment]
Hi @ayelen3976 👋
Thanks for opening this issue.
How did you install Postgres? (E.g did you use Homebrew?)
You appear to have an existing instance running?

**Comment by ayelen3976** [comment]
@nelsonic I didnt use Homebrew . I installed from the page and donwload the option to macbook.  I used to start with this command >> psql -U postgres. now I want enter with the same command but I cant . because postgres say "port in use"

**Comment by nelsonic** [comment]
@ayelen3976 if you run `sudo pkill -u postgres` as per https://github.com/dwyl/learn-postgresql/issues/60#issuecomment-602025009 does it kill your Postgres DB server?  💭

**Comment by ayelen3976** [comment]
@nelsonic didnt work , but I restart my laptop and the db of postgres work . thankss anyway

**Comment by nelsonic** [comment]
@ayelen3976 strange. But glad you made progress. 🙌

**Comment by nelsonic** [comment]
Nothing like turning it off an on again. ♻️ 

Closing this issue as there is nothing else we can do for it. 👍
