### ISSUE TITLE
Installation process on MacOS is outdated

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/learn-postgresql#86]
Thank you for the repo, it's mighty useful!

I'm following the readme file and I noticed the installation process in MacOS is slightly different. The wizard now only calls for server initialization and it's up and running.
Additionally, the `psql` command line doesn't come "out-of-the-box" in recent versions and some commands to add it to the $PATH variable are needed.

I can pull a quick PR to fix this 😄 .

**Comment by nelsonic** [comment]
Please go ahead and PR the update. 👍 
Remember to follow https://sembr.org/ and not make lines/blocks of text too long. 📝 
Horrizontal scrolling is _horrible_. 😜
